/*
Problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

whiteboard:
go up to the term whose value is 4000000 or less
add all of the even-valued terms
*/

//Iterative attempt
// finds answer for n, which should be set to 4000000 in this case
var addEvenFib = function(n) {
  var first = 0;
  var second = 1;
  var fib = first + second;
  var sum = 0;
  while (fib <= n) {
    if (fib % 2 === 0) {
      sum += fib;
    }
    first = second;
    second = fib;
    fib = first + second
  }
  return sum;
}

//console.log(addEvenFib(4000000)); ===>  SOLUTION: 4613732
